In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
file =  pd.read_csv("netflix-rotten-tomatoes-metacritic-imdb.csv")
file.head()

,Title,Genre,Tags,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,...,Netflix Release Date,Production House,Netflix Link,IMDb Link,Summary,IMDb Votes,Image,Poster,TMDb Trailer,Trailer Site
0,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Comedy Programmes,Romantic TV Comedies,Horror ...","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,John Ajvide Lindqvist,...,2021-03-04,"Canal+, Sandrew Metronome",https://www.netflix.com/watch/81415947,https://www.imdb.com/title/tt1139797,A med student with a supernatural gift tries t...,205926.0,https://occ-0-4708-64.1.nflxso.net/dnm/api/v6/...,https://m.media-amazon.com/images/M/MV5BOWM4NT...,NaN,NaN
1,HOW TO BUILD A GIRL,Comedy,"Dramas,Comedies,Films Based on Books,British",English,Movie,7.0,Canada,1-2 hour,Coky Giedroyc,Caitlin Moran,...,2021-03-04,"Film 4, Monumental Pictures, Lionsgate",https://www.netflix.com/watch/81041267,https://www.imdb.com/title/tt4193072,"When nerdy Johanna moves to London, things get...",2838.0,https://occ-0-1081-999.1.nflxso.net/dnm/api/v6...,https://m.media-amazon.com/images/M/MV5BZGUyN2...,https://www.youtube.com/watch?v=eIbcxPy4okQ,YouTube
2,Centigrade,"Drama, Thriller",Thrillers,English,Movie,6.4,Canada,1-2 hour,Brendan Walsh,"Brendan Walsh, Daley Nixon",...,2021-03-04,NaN,https://www.netflix.com/watch/81305978,https://www.imdb.com/title/tt8945942,"Trapped in a frozen car during a blizzard, a p...",1720.0,https://occ-0-1081-999.1.nflxso.net/dnm/api/v6...,https://m.media-amazon.com/images/M/MV5BODM2MD...,https://www.youtube.com/watch?v=0RvV7TNUlkQ,YouTube
3,ANNE+,Drama,"TV Dramas,Romantic TV Dramas,Dutch TV Shows",Turkish,Series,7.7,"Belgium,Netherlands",< 30 minutes,NaN,NaN,...,2021-03-04,NaN,https://www.netflix.com/watch/81336456,https://www.imdb.com/title/tt6132758,"Upon moving into a new place, a 20-something r...",1147.0,https://occ-0-1489-1490.1.nflxso.net/dnm/api/v...,https://m.media-amazon.com/images/M/MV5BNWRkMz...,NaN,NaN
4,Moxie,"Animation, Short, Drama","Social Issue Dramas,Teen Movies,Dramas,Comedie...",English,Movie,8.1,"Lithuania,Poland,France,Iceland,Italy,Spain,Gr...",1-2 hour,Stephen Irwin,NaN,...,2021-03-04,NaN,https://www.netflix.com/watch/81078393,https://www.imdb.com/title/tt2023611,Inspired by her moms rebellious past and a con...,63.0,https://occ-0-4039-1500.1.nflxso.net/dnm/api/v...,https://m.media-amazon.com/images/M/MV5BODYyNW...,NaN,NaN

In [35]:
file.describe()

,Hidden Gem Score,IMDb Score,Rotten Tomatoes Score,Metacritic Score,Awards Received,Awards Nominated For,IMDb Votes
count,13379.000000,13381.000000,6382.000000,4336.000000,6075.000000,7661.000000,1.337900e+04
mean,5.937551,6.496054,59.523034,56.813653,8.764444,13.983161,4.272841e+04
std,2.250202,1.146910,26.999173,17.582545,18.311171,29.821052,1.257012e+05
min,0.600000,1.000000,0.000000,5.000000,1.000000,1.000000,5.000000e+00
25%,3.800000,5.800000,38.000000,44.000000,1.000000,2.000000,4.035000e+02
50%,6.800000,6.600000,64.000000,57.000000,3.000000,5.000000,2.322000e+03
75%,7.900000,7.300000,83.000000,70.000000,8.000000,12.000000,2.089050e+04
max,9.800000,9.700000,100.000000,100.000000,300.000000,386.000000,2.354197e+06

In [36]:
file.describe

<bound method NDFrame.describe of                                            Title  \
0                               Lets Fight Ghost
1                            HOW TO BUILD A GIRL
2                                     Centigrade
3                                          ANNE+
4                                          Moxie
...                                          ...
15475                     K-POP Extreme Survival
15476            DreamWorks Shreks Swamp Stories
15477  DreamWorks Happy Holidays from Madagascar
15478                DreamWorks Holiday Classics
15479   DreamWorks Kung Fu Panda Awesome Secrets

                                        Genre  \
0      Crime, Drama, Fantasy, Horror, Romance
1                                      Comedy
2                             Drama, Thriller
3                                       Drama
4                     Animation, Short, Drama
...                                       ...
15475                                     NaN
15476                                     NaN
15477               Animation, Comedy, Family
15478               Animation, Comedy, Family
15479       Animation, Action, Comedy, Family

                                                    Tags         Languages  \
0      Comedy Programmes,Romantic TV Comedies,Horror ...  Swedish, Spanish
1           Dramas,Comedies,Films Based on Books,British           English
2                                              Thrillers           English
3            TV Dramas,Romantic TV Dramas,Dutch TV Shows           Turkish
4      Social Issue Dramas,Teen Movies,Dramas,Comedie...           English
...                                                  ...               ...
15475  TV Dramas,TV Programmes,TV Comedies,Romantic T...               NaN
15476  Animal Tales,Family Comedies,Family Adventures...               NaN
15477  TV Comedies,Kids TV,Animal Tales,TV Cartoons,T...           English
15478  TV Comedies,Kids TV,TV Cartoons,TV Programmes,...           English
15479  TV Comedies,Kids TV,Animal Tales,TV Cartoons,T...           English

      Series or Movie  Hidden Gem Score  \
0              Series               4.3
1               Movie               7.0
2               Movie               6.4
3              Series               7.7
4               Movie               8.1
...               ...               ...
15475          Series               NaN
15476          Series               NaN
15477          Series               8.4
15478          Series               8.2
15479          Series               8.1

                                    Country Availability       Runtime  \
0                                               Thailand  < 30 minutes
1                                                 Canada      1-2 hour
2                                                 Canada      1-2 hour
3                                    Belgium,Netherlands  < 30 minutes
4      Lithuania,Poland,France,Iceland,Italy,Spain,Gr...      1-2 hour
...                                                  ...           ...
15475  South Korea,Argentina,United Kingdom,Australia...  < 30 minutes
15476  Russia,Hong Kong,Hungary,Australia,South Korea...  < 30 minutes
15477  Belgium,Switzerland,United States,Germany,Unit...  < 30 minutes
15478  Belgium,Switzerland,Germany,Argentina,United K...  < 30 minutes
15479  Belgium,Switzerland,Germany,United Kingdom,Fra...  < 30 minutes

              Director                      Writer  ... Netflix Release Date  \
0      Tomas Alfredson       John Ajvide Lindqvist  ...           2021-03-04
1        Coky Giedroyc               Caitlin Moran  ...           2021-03-04
2        Brendan Walsh  Brendan Walsh, Daley Nixon  ...           2021-03-04
3                  NaN                         NaN  ...           2021-03-04
4        Stephen Irwin                         NaN  ...           2021-03-04
...                ...                         ...  ...                  ...
15475              NaN                         NaN  ...           2015-04-14
15476              NaN                         NaN  ...           2015-04-14
15477              NaN                         NaN  ...           2015-04-14
15478              NaN                         NaN  ...           2015-04-14
15479              NaN                         NaN  ...           2015-04-14

                             Production House  \
0                   Canal+, Sandrew Metronome
1      Film 4, Monumental Pictures, Lionsgate
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
15475                                     NaN
15476                                     NaN
15477                                     NaN
15478                                     Fox
15479                                     NaN

                                 Netflix Link  \
0      https://www.netflix.com/watch/81415947
1      https://www.netflix.com/watch/81041267
2      https://www.netflix.com/watch/81305978
3      https://www.netflix.com/watch/81336456
4      https://www.netflix.com/watch/81078393
...                                       ...
15475  https://www.netflix.com/watch/80031595
15476  https://www.netflix.com/watch/70242630
15477  https://www.netflix.com/watch/70259784
15478  https://www.netflix.com/watch/70221348
15479  https://www.netflix.com/watch/70241791

                                  IMDb Link  \
0      https://www.imdb.com/title/tt1139797
1      https://www.imdb.com/title/tt4193072
2      https://www.imdb.com/title/tt8945942
3      https://www.imdb.com/title/tt6132758
4      https://www.imdb.com/title/tt2023611
...                                     ...
15475                                   NaN
15476                                   NaN
15477                                   NaN
15478                                   NaN
15479                                   NaN

                                                 Summary  IMDb Votes  \
0      A med student with a supernatural gift tries t...    205926.0
1      When nerdy Johanna moves to London, things get...      2838.0
2      Trapped in a frozen car during a blizzard, a p...      1720.0
3      Upon moving into a new place, a 20-something r...      1147.0
4      Inspired by her moms rebellious past and a con...        63.0
...                                                  ...         ...
15475  Seung Yeon decides to chase her dream of becom...         NaN
15476  Shrek celebrates Halloween, Puss in Boots is c...         NaN
15477  Madagascar goes wild with holiday spirit in th...        71.0
15478  Join your DreamWorks friends for these four ho...        82.0
15479  In this pair of adventures, Po tells the story...        17.0

                                                   Image  \
0      https://occ-0-4708-64.1.nflxso.net/dnm/api/v6/...
1      https://occ-0-1081-999.1.nflxso.net/dnm/api/v6...
2      https://occ-0-1081-999.1.nflxso.net/dnm/api/v6...
3      https://occ-0-1489-1490.1.nflxso.net/dnm/api/v...
4      https://occ-0-4039-1500.1.nflxso.net/dnm/api/v...
...                                                  ...
15475  https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/...
15476  https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/...
15477  https://occ-0-2773-2774.1.nflxso.net/dnm/api/v...
15478  https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/...
15479  https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/...

                                                  Poster  \
0      https://m.media-amazon.com/images/M/MV5BOWM4NT...
1      https://m.media-amazon.com/images/M/MV5BZGUyN2...
2      https://m.media-amazon.com/images/M/MV5BODM2MD...
3      https://m.media-amazon.com/images/M/MV5BNWRkMz...
4      https://m.media-amazon.com/images/M/MV5BODYyNW...
...                                                  ...
15475                                                NaN
15476                                                NaN
15477                                                NaN
15478                                                NaN
15479                                                NaN

                                      TMDb Trailer Trailer Site
0                                              NaN          NaN
1      https://www.youtube.com/watch?v=eIbcxPy4okQ      YouTube
2      https://www.youtube.com/watch?v=0RvV7TNUlkQ      YouTube
3                                              NaN          NaN
4                                              NaN          NaN
...                                            ...          ...
15475                                          NaN          NaN
15476                                          NaN          NaN
15477                                          NaN          NaN
15478                                          NaN          NaN
15479                                          NaN          NaN

[15480 rows x 29 columns]>

Tere are total number of 15479 rows and 29 columns

## Checking Data types and Column names

In [37]:
file.dtypes

Title                     object
Genre                     object
Tags                      object
Languages                 object
Series or Movie           object
Hidden Gem Score         float64
Country Availability      object
Runtime                   object
Director                  object
Writer                    object
Actors                    object
View Rating               object
IMDb Score               float64
Rotten Tomatoes Score    float64
Metacritic Score         float64
Awards Received          float64
Awards Nominated For     float64
Boxoffice                 object
Release Date              object
Netflix Release Date      object
Production House          object
Netflix Link              object
IMDb Link                 object
Summary                   object
IMDb Votes               float64
Image                     object
Poster                    object
TMDb Trailer              object
Trailer Site              object
dtype: object

In [38]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15480 entries, 0 to 15479
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  15480 non-null  object
 1   Genre                  13770 non-null  object
 2   Tags                   15413 non-null  object
 3   Languages              13545 non-null  object
 4   Series or Movie        15480 non-null  object
 5   Hidden Gem Score       13379 non-null  float64
 6   Country Availability   15461 non-null  object
 7   Runtime                15479 non-null  object
 8   Director               10772 non-null  object
 9   Writer                 11150 non-null  object
 10  Actors                 13555 non-null  object
 11  View Rating            8456 non-null   object
 12  IMDb Score             13381 non-null  float64
 13  Rotten Tomatoes Score  6382 non-null   float64
 14  Metacritic Score       4336 non-null   float64
 15  Awards Received        6075 non-null   float64
 16  Awards Nominated For   7661 non-null   float64
 17  Boxoffice              4007 non-null   object
 18  Release Date           13373 non-null  object
 19  Netflix Release Date   15480 non-null  object
 20  Production House       5149 non-null   object
 21  Netflix Link           15480 non-null  object
 22  IMDb Link              13177 non-null  object
 23  Summary                15471 non-null  object
 24  IMDb Votes             13379 non-null  float64
 25  Image                  15480 non-null  object
 26  Poster                 11842 non-null  object
 27  TMDb Trailer           7194 non-null   object
 28  Trailer Site           7194 non-null   object
dtypes: float64(7), object(22)
memory usage: 3.4+ MB

Here we can see, the Non-NULL and NULL

In [39]:
# Checking out the NULL values in the given dataset
file.isnull().sum()

Title                        0
Genre                     1710
Tags                        67
Languages                 1935
Series or Movie              0
Hidden Gem Score          2101
Country Availability        19
Runtime                      1
Director                  4708
Writer                    4330
Actors                    1925
View Rating               7024
IMDb Score                2099
Rotten Tomatoes Score     9098
Metacritic Score         11144
Awards Received           9405
Awards Nominated For      7819
Boxoffice                11473
Release Date              2107
Netflix Release Date         0
Production House         10331
Netflix Link                 0
IMDb Link                 2303
Summary                      9
IMDb Votes                2101
Image                        0
Poster                    3638
TMDb Trailer              8286
Trailer Site              8286
dtype: int64

Here we can see the NULL values in eah column.

**Thus we will be dropping the columns which have NULL values and we dont need them.**
Here, most of the columns with **maximum** number of `NULL VALUES` are :
1. Metacritic Score         11144
2. Boxoffice                11473
3. Production House         10331
4. Netflix Link                 0 (we don't need this column)
5. IMDb Link                 2303

In [42]:
# Dropping these columns from the dataset
file = file.drop(columns = ['Metacritic Score', 'Boxoffice', 'Production House', 'Netflix Link', 'IMDb Link'], axis = 1)

KeyError: "['Metacritic Score' 'Boxoffice' 'Production House' 'Netflix Link'\n 'IMDb Link'] not found in axis"

In [43]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15480 entries, 0 to 15479
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  15480 non-null  object
 1   Genre                  13770 non-null  object
 2   Tags                   15413 non-null  object
 3   Languages              13545 non-null  object
 4   Series or Movie        15480 non-null  object
 5   Hidden Gem Score       13379 non-null  float64
 6   Country Availability   15461 non-null  object
 7   Runtime                15479 non-null  object
 8   Director               10772 non-null  object
 9   Writer                 11150 non-null  object
 10  Actors                 13555 non-null  object
 11  View Rating            8456 non-null   object
 12  IMDb Score             13381 non-null  float64
 13  Rotten Tomatoes Score  6382 non-null   float64
 14  Awards Received        6075 non-null   float64
 15  Awards Nominated For   7661 non-null   float64
 16  Release Date           13373 non-null  object
 17  Netflix Release Date   15480 non-null  object
 18  Summary                15471 non-null  object
 19  IMDb Votes             13379 non-null  float64
 20  Image                  15480 non-null  object
 21  Poster                 11842 non-null  object
 22  TMDb Trailer           7194 non-null   object
 23  Trailer Site           7194 non-null   object
dtypes: float64(6), object(18)
memory usage: 2.8+ MB

As here we have dropped 5 columns from the Dataset, as they were of no use to us.

In [44]:
# Creting the ID columns for each row.
st = 1
file.insert(0, 'ID', range(st, st + file.shape[0]))

In [29]:
file.head()

,ID,Title,Genre,Tags,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,...,Awards Received,Awards Nominated For,Release Date,Netflix Release Date,Summary,IMDb Votes,Image,Poster,TMDb Trailer,Trailer Site
0,1,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Comedy Programmes,Romantic TV Comedies,Horror ...","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,...,74.0,57.0,12 Dec 2008,2021-03-04,A med student with a supernatural gift tries t...,205926.0,https://occ-0-4708-64.1.nflxso.net/dnm/api/v6/...,https://m.media-amazon.com/images/M/MV5BOWM4NT...,NaN,NaN
1,2,HOW TO BUILD A GIRL,Comedy,"Dramas,Comedies,Films Based on Books,British",English,Movie,7.0,Canada,1-2 hour,Coky Giedroyc,...,1.0,NaN,08 May 2020,2021-03-04,"When nerdy Johanna moves to London, things get...",2838.0,https://occ-0-1081-999.1.nflxso.net/dnm/api/v6...,https://m.media-amazon.com/images/M/MV5BZGUyN2...,https://www.youtube.com/watch?v=eIbcxPy4okQ,YouTube
2,3,Centigrade,"Drama, Thriller",Thrillers,English,Movie,6.4,Canada,1-2 hour,Brendan Walsh,...,NaN,NaN,28 Aug 2020,2021-03-04,"Trapped in a frozen car during a blizzard, a p...",1720.0,https://occ-0-1081-999.1.nflxso.net/dnm/api/v6...,https://m.media-amazon.com/images/M/MV5BODM2MD...,https://www.youtube.com/watch?v=0RvV7TNUlkQ,YouTube
3,4,ANNE+,Drama,"TV Dramas,Romantic TV Dramas,Dutch TV Shows",Turkish,Series,7.7,"Belgium,Netherlands",< 30 minutes,NaN,...,1.0,NaN,01 Oct 2016,2021-03-04,"Upon moving into a new place, a 20-something r...",1147.0,https://occ-0-1489-1490.1.nflxso.net/dnm/api/v...,https://m.media-amazon.com/images/M/MV5BNWRkMz...,NaN,NaN
4,5,Moxie,"Animation, Short, Drama","Social Issue Dramas,Teen Movies,Dramas,Comedie...",English,Movie,8.1,"Lithuania,Poland,France,Iceland,Italy,Spain,Gr...",1-2 hour,Stephen Irwin,...,NaN,4.0,22 Sep 2011,2021-03-04,Inspired by her moms rebellious past and a con...,63.0,https://occ-0-4039-1500.1.nflxso.net/dnm/api/v...,https://m.media-amazon.com/images/M/MV5BODYyNW...,NaN,NaN

In [45]:
# Deleting the NULL values from the dataset.
file.dropna(axis=0, how='any')

,ID,Title,Genre,Tags,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,...,Awards Received,Awards Nominated For,Release Date,Netflix Release Date,Summary,IMDb Votes,Image,Poster,TMDb Trailer,Trailer Site
15,16,Joker,"Crime, Drama, Thriller","Dark Comedies,Crime Comedies,Dramas,Comedies,C...",English,Movie,3.5,"Lithuania,Poland,France,Italy,Spain,Greece,Bel...",1-2 hour,Todd Phillips,...,112.0,228.0,04 Oct 2019,2021-03-03,A practical jokers fake kidnapping at a bachel...,951938.0,https://occ-0-2851-41.1.nflxso.net/dnm/api/v6/...,https://m.media-amazon.com/images/M/MV5BNGVjNW...,https://www.youtube.com/watch?v=t433PEQGErc,YouTube
16,17,I,"Action, Adventure, Fantasy, Sci-Fi","Dramas,Swedish Movies","English, Sanskrit",Movie,2.8,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",1-2 hour,George Lucas,...,26.0,69.0,19 May 1999,2021-03-03,A young man seeking his identity begins a roma...,733336.0,https://occ-0-2851-41.1.nflxso.net/dnm/api/v6/...,https://m.media-amazon.com/images/M/MV5BYTRhNj...,https://www.youtube.com/watch?v=bD7bpG-zDJQ,YouTube
17,18,Harrys Daughters,"Adventure, Drama, Fantasy, Mystery","Dramas,Swedish Movies",English,Movie,4.4,"Lithuania,Poland,France,Italy,Spain,Greece,Cze...",1-2 hour,David Yates,...,46.0,94.0,15 Jul 2011,2021-03-03,"As two sisters both experience pregnancy, trag...",766594.0,https://occ-0-2851-41.1.nflxso.net/dnm/api/v6/...,https://m.media-amazon.com/images/M/MV5BMGVmMW...,https://www.youtube.com/watch?v=5NYt1qirBWg,YouTube
28,29,The Closet,Comedy,"Korean Movies,Horror Movies,Mysteries",French,Movie,3.8,South Korea,1-2 hour,Francis Veber,...,1.0,1.0,10 Aug 2001,2021-03-01,A recent widowers move into a new house takes ...,16657.0,https://occ-0-395-988.1.nflxso.net/dnm/api/v6/...,https://m.media-amazon.com/images/M/MV5BMGRmNz...,https://www.youtube.com/watch?v=ou9YG0fUztA,YouTube
60,61,Ordinary People,Drama,"Korean Movies,Thriller Movies,Crime Thrillers",English,Movie,4.2,South Korea,1-2 hour,Robert Redford,...,19.0,14.0,19 Sep 1980,2021-02-28,During a probe into a missing high school stud...,47265.0,https://occ-0-1361-988.1.nflxso.net/dnm/api/v6...,https://m.media-amazon.com/images/M/MV5BNWU3MD...,https://www.youtube.com/watch?v=BdjlLq1tqmU,YouTube
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15459,15460,One Chance,"Biography, Comedy, Drama, Music","Dramas,Biographical Dramas,Dramas based on rea...","English, Italian",Movie,3.0,"Japan,Malaysia",1-2 hour,David Frankel,...,3.0,5.0,25 Oct 2013,2015-04-14,"From shop worker to worldwide phenomena, this ...",11536.0,https://occ-0-768-769.1.nflxso.net/dnm/api/v6/...,https://images-na.ssl-images-amazon.com/images...,https://www.youtube.com/watch?v=OdYt32WlvTY,YouTube
15460,15461,The Twilight Saga: Breaking Dawn: Part 1,"Adventure, Drama, Fantasy, Romance, Thriller","Dramas,Romantic Dramas,Dramas based on a book,...","English, Portuguese",Movie,2.0,"Canada,Romania,Japan,Switzerland,United Kingdo...",> 2 hrs,Bill Condon,...,11.0,22.0,18 Nov 2011,2015-04-14,Not long after immortal soul mates Bella Swan ...,224372.0,https://occ-0-2773-2774.1.nflxso.net/dnm/api/v...,https://images-na.ssl-images-amazon.com/images...,https://www.youtube.com/watch?v=PQNLfo-SOR4,YouTube
15461,15462,One for the Money,"Action, Comedy, Crime, Thriller","Romantic Comedies,Action Comedies,Comedies,Pol...",English,Movie,1.3,Canada,1-2 hour,Julie Anne Robinson,...,1.0,1.0,27 Jan 2012,2015-04-14,"A divorced, unemployed woman becomes a bounty ...",40841.0,https://occ-0-2773-2774.1.nflxso.net/dnm/api/v...,https://images-na.ssl-images-amazon.com/images...,https://www.youtube.com/watch?v=VqaDZsHnpJA,YouTube
15462,15463,4.3.2.1,"Crime, Thriller","Thrillers,Steamy Thrillers,Police Thrillers,Po...",English,Movie,2.4,India,1-2 hour,"Mark Davis, Noel Clarke",...,1.0,3.0,02 Jun 2010,2015-04-14,The clock is ticking as four young women have ...,10370.0,https://occ-0-2042-299.1.nflxso.net/dnm/api/v6...,https://images-na.ssl-images-amazon.com/images...,https://www.youtube.com/watch?v=pXG7TJ6aPnM,YouTube
15463,15464,13,"Crime, Drama, Thriller","Thrillers,Gangster Films,Police Thrillers,Poli...",English,Movie,1.6,"Romania,Hungary,Czech Republic,Slovakia",1-2 hour,GÃ©la Babluani,...,1.0,1.0,01 Mar 2010,2015-04-14,"After assuming a dead persons identity, a call...",40425.0,https://occ-0-2773-2774.1.nflxso.net/dnm/api/v...,https://images-na.ssl-images-amazon.com/images...,https://www.youtube.com/watch?v=Y41fFj-P4jI,YouTube

In [46]:
file.head(2)

,ID,Title,Genre,Tags,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,...,Awards Received,Awards Nominated For,Release Date,Netflix Release Date,Summary,IMDb Votes,Image,Poster,TMDb Trailer,Trailer Site
0,1,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Comedy Programmes,Romantic TV Comedies,Horror ...","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,...,74.0,57.0,12 Dec 2008,2021-03-04,A med student with a supernatural gift tries t...,205926.0,https://occ-0-4708-64.1.nflxso.net/dnm/api/v6/...,https://m.media-amazon.com/images/M/MV5BOWM4NT...,NaN,NaN
1,2,HOW TO BUILD A GIRL,Comedy,"Dramas,Comedies,Films Based on Books,British",English,Movie,7.0,Canada,1-2 hour,Coky Giedroyc,...,1.0,NaN,08 May 2020,2021-03-04,"When nerdy Johanna moves to London, things get...",2838.0,https://occ-0-1081-999.1.nflxso.net/dnm/api/v6...,https://m.media-amazon.com/images/M/MV5BZGUyN2...,https://www.youtube.com/watch?v=eIbcxPy4okQ,YouTube